name: Release

on: # yamllint disable-line rule:truthy
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        node-version: ['lts/*']
      fail-fast: false
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: npm install & build
        run: |
          npm install
          npm run build --if-present

      - name: Upload checksums
        uses: actions/upload-artifact@v3
        with:
          name: checksums
          path: dist/checksums.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: dist/*
  
  publish_aur_package:
    needs:
      - release
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        node-version: ['lts/*']
      fail-fast: false
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Download checksums
        uses: actions/download-artifact@v3
        with:
          name: checksums
          path: ./checksums.txt

      - name: Generate PKGBUILD
        env:
          RELEASE_TAG: ${{ github.ref_name }}
          CHECKSUM_FILE: ./checksums.txt
          OUTPUT_DIR: ./pkgbuild/gluctl-bin
        run: ./scripts/generate-pkgbuild.mjs

      - name: Publish gluctl-bin to the AUR
        uses: KSXGitHub/github-actions-deploy-aur@v2.2.3
        with:
          pkgname: gluctl-bin
          pkgbuild: ./pkgbuild/gluctl-bin/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update to ${{ github.ref_name }}"
          force_push: 'true'
